### ISSUE TITLE
Show job aliases?

### ISSUE THREAD

**Issue by rdrighetto** [dzyla/Follow_Relion_gracefully#4]
Hi Dawid,

Thanks for sharing this awesome tool!

Would it be possible to show the job aliases instead of the job numbers? Or maybe have an option to switch?
Apologies if this is already available somewhere, please let me know.

Cheers,
Ricardo

**Comment by dzyla** [comment]
Hi Ricardo,

Thank you! I'm glad you find it useful!

I have made the necessary adjustments so that the Alias is now being displayed on the job radio selection and is also printed below the job type/number. Please let me know if this is what you have in mind!

You can pull the code from the repo and check it.

I would be more than happy to make further improvements or add any additional statistics that you would find helpful!

Best,
Dawid

**Comment by rdrighetto** [comment]
That was fast! Thank you so much Dawid, this is great!
